name: CI - Lint -> Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"

      - name: Check Poetry installation
        run: poetry --version

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run Ruff (lint)
        run: poetry run ruff check .

      - name: Check formatting
        run: poetry run ruff format --check .

      #- name: Run mypy
      #  run: poetry run mypy .

  tests:
    runs-on: ubuntu-latest
    needs: quality-check

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Check Poetry installation
        run: poetry --version

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run pytest
        if: hashFiles('**/test_*.py') != ''
        run: |
          echo "Tests detected, running pytest"
          poetry run pytest --cov=app --cov-report=term-missing
